services:
  db:
    image: postgres:15-alpine
    container_name: sanic_payment_db
    environment:
      POSTGRES_DB: sanic_payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sanic_payment_api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=sanic_payment_db
      - SECRET_KEY=your-secret-key-change-in-production
      - JWT_SECRET=jwt-secret-key-change-in-production
      - WEBHOOK_SECRET=gfdmhghif38yrf9ew0jkf32
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: python -m app.main

volumes:
  postgres_data:
